name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## What's Changed

  $CHANGES
categories:
  - title: '💥 Breaking'
    labels:
      - breaking
  - title: '✨ Features'
    labels:
      - feature
  - title: '🐛 Bug Fixes'
    labels:
      - bug
  - title: '👷 Maintenance'
    labels:
      - chore
  - title: '📝 Documentation'
    labels:
      - docs
  - title: '📦 Dependency Updates'
    labels:
      - 'dependency'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'chore'
      - 'bug'
      - 'docs'
      - 'dependency'
  default: patch
